"""Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms."""

def Fibonacci(upperbound):
    listofnumbers = [1,1]
    evennumbers = []
    while listofnumbers[-1] <= upperbound:
        add = listofnumbers[-1] + listofnumbers[-2]
        listofnumbers.append(add)
        if add % 2 == 0:
            evennumbers.append(add)
    total = 0
    for value in evennumbers:
       
        total += value
        
    return total
        
print(Fibonacci(4000000))
